artifact_uri: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/ml_life_cycle/remote_server_uri/0/6e4915a2ee6e48c29654197071409b3b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6e4915a2ee6e48c29654197071409b3b
run_name: KNN_Audio_Features_2
run_uuid: 6e4915a2ee6e48c29654197071409b3b
source_name: ''
source_type: 4
source_version: ''
start_time: 1697104486843
status: 1
tags: []
user_id: clayb
