aliases: []
creation_timestamp: 1697104866994
current_stage: None
description: null
last_updated_timestamp: 1697104866994
name: K-NN
run_id: b058319d877e4bf49f3c1ed866b318c5
run_link: null
source: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/ml_life_cycle/remote_server_uri/149871096565536443/b058319d877e4bf49f3c1ed866b318c5/artifacts/sklearn-model
status: READY
status_message: null
user_id: null
version: 2
