aliases: []
creation_timestamp: 1697088048050
current_stage: None
description: null
last_updated_timestamp: 1697088048050
name: K-NN
run_id: acdb16915ba3405ab66a86c6b65f6365
run_link: null
source: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/data_augmentation/reinforcement_learning/pipeline/data_augmentation/K-NN_Music_Features_2/0/acdb16915ba3405ab66a86c6b65f6365/artifacts/sklearn-model
status: READY
status_message: null
user_id: null
version: 1
