artifact_location: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/ml_life_cycle/remote_server_uri/146594534046359300
creation_time: 1697105778845
experiment_id: '146594534046359300'
last_update_time: 1697105778845
lifecycle_stage: active
name: http://127.0.0.1:5000
