artifact_location: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/data_augmentation/reinforcement_learning/pipeline/data_augmentation/K-NN_Music_Features_2/755551824411776114
creation_time: 1697089283277
experiment_id: '755551824411776114'
last_update_time: 1697089283277
lifecycle_stage: active
name: '729553857325031014'
