artifact_uri: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/data_augmentation/reinforcement_learning/pipeline/data_augmentation/K-NN_Music_Features/0/7f9bcc26945947b7b2b1956344575ad0/artifacts
end_time: 1697087633901
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7f9bcc26945947b7b2b1956344575ad0
run_name: KNN_Audio_Features_2
run_uuid: 7f9bcc26945947b7b2b1956344575ad0
source_name: ''
source_type: 4
source_version: ''
start_time: 1697087548766
status: 3
tags: []
user_id: clayb
