artifact_uri: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/data_augmentation/reinforcement_learning/pipeline/data_augmentation/K-NN_Music_Features_2/0/acdb16915ba3405ab66a86c6b65f6365/artifacts
end_time: 1697088805087
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: acdb16915ba3405ab66a86c6b65f6365
run_name: KNN_Audio_Features_2
run_uuid: acdb16915ba3405ab66a86c6b65f6365
source_name: ''
source_type: 4
source_version: ''
start_time: 1697087723660
status: 3
tags: []
user_id: clayb
