artifact_location: file:///c:/Users/clayb/Documents/GitHub/holbertonschool-machine_learning/reinforcement_learning/pipeline/ml_life_cycle/remote_server_uri/149871096565536443
creation_time: 1697104473290
experiment_id: '149871096565536443'
last_update_time: 1697104473290
lifecycle_stage: active
name: KNN
